export { };

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      BROWSER: "chrome_latest" | "firefox" | "Safari" | "chrome_latestlt",
      ENV: "stg" | "prod" | "dev",
      TAGS: string,
      BASEURL: string,
      API_BASE_URL: string,
      APPSYNC_BASE_URL: string,
      GRAPHQL: string,
      path_key_cipher: string,
      version: string,
      revision: string,
      startDate: string,
      finishDate: string,
      path_recaptcha: string,
      path_auth_service_public_key: string,
      path_auth_service_JWT: string,
      tokenRecaptcha: string,
      deviceSerial: string,
      cities: string,
      agreement_taxes: string,
      consult_public_services_information: string,
      blacklist: string,
      logout: string,
      penalty_consultation: string,
      payments_history: string,
      administration_billers: string,
      registered_services: string,
      affiliations_products: string,
      customer_product: string,
      consult_account: string,
      bank_list_inscription: string,
      consult_product_by_cellphone: string,
      trasnfer: string,
      advancetc: string,
      uuid: string,
      gpswd_forgot: string,
      movements: string,
      product_info: string,
      administrationPseCommerce: string,
      secure_data: string,
      product: string,
      donations: string,
      unreg_xfer_founds: string,
      aesInitialVector: string,
      privateKey: string,
      canary: string,
      mock: string,
      viewPort_width: string,
      viewPort_height: string,
      updateSchema: string,
      second_factor: string,
      financial: string,
      favorites_transactions: string,
      pfm_balance_products: string,
      terms_agreement_list: string,
      aval_key_for_id: string,
      notification_login: string,
      enrollment_public_key: string,
      conversation_start: string,
      fiduocc: string,
      fidu_product_info: string,
      tax_info: string,
      loans_payments: string,
      pay_tax: string,
      credit_loans_payments: string,
      query_scheduled_payments: string,
      schedule_agreement: string,
      traveling_customer_create: string,
      traveling_customer_consult: string,
      customer_inquiry_mdm_data: string,
      authentication_otp_otp: string,
      admin_limits: string,
      inquiries_path: string,
      inqueries_xfer: string,
      schedule_transfer: string,
      user_config: string,
      phone_product_path: string,
      transfer_online_send: string,
      customer_loyalty: string,
      loyalty_transactions: string
      transfer_online_history: string,
      enrollment_user: string,
      accessKey: string,
      ltDevice: string,
      apiKeyHeader : string,
      HEAD: "true" | "false"
    }
  }
}
